include:
  - project: kkowa/ci-templates
    ref: main
    file: /templates/application.gitlab-ci.yml

docker-build:cache:
  extends: .docker-build
  stage: build
  variables:
    TARGET: build
    TAGS: >
      ${CI_COMMIT_REF_SLUG}-cache

docker-build:development:
  needs:
    - docker-build:cache
  variables:
    EXTRA_CACHE_SOURCES: >
      ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-cache

docker-build:production:
  needs:
    - docker-build:cache
  variables:
    EXTRA_CACHE_SOURCES: >
      ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-cache

app-ci:
  variables:
    TEST_REPORT_FILE: ${CI_PROJECT_DIR}/.reports/*
