/*
 * kkowa Open API
 *
 *  This page is automatically generated documentation of kkowa server's Open API.  Features are support by GraphQL. API is designed for communication between organization components to perform simple tasks with simple HTTP calls only. Advanced users may also use this API using their API keys to build their own programs.  For more information not described in this page, please contact organization or project administrators or maintainers.     
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Document : Model schema for `Document` model.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Document {
    #[serde(rename = "id")]
    pub id: String,
}

impl Document {
    /// Model schema for `Document` model.
    pub fn new(id: String) -> Document {
        Document {
            id,
        }
    }
}


