/*
 * kkowa Open API
 *
 *  This page is automatically generated documentation of kkowa server's Open API.  Features are support by GraphQL. API is designed for communication between organization components to perform simple tasks with simple HTTP calls only. Advanced users may also use this API using their API keys to build their own programs.  For more information not described in this page, please contact organization or project administrators or maintainers.     
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ValidationError {
    #[serde(rename = "loc")]
    pub loc: Vec<crate::models::LocationInner>,
    #[serde(rename = "msg")]
    pub msg: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl ValidationError {
    pub fn new(loc: Vec<crate::models::LocationInner>, msg: String, r#type: String) -> ValidationError {
        ValidationError {
            loc,
            msg,
            r#type,
        }
    }
}


